# Generated by Django 4.1.7 on 2023-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID1', models.IntegerField(default=0, null=True)),
                ('O_price', models.BigIntegerField(default=0, null=True)),
                ('C_price', models.BigIntegerField(default=0, null=True)),
                ('Opost_price', models.IntegerField(default=0, null=True)),
                ('Cpost_price', models.IntegerField(default=0, null=True)),
                ('date', models.CharField(default='date', max_length=100, null=True)),
                ('Oquantity', models.IntegerField(default=0, null=True)),
                ('Cquantity', models.IntegerField(default=0, null=True)),
                ('item_name', models.TextField(default='item', max_length=10000, null=True)),
                ('Citem_name', models.TextField(default='item', max_length=10000, null=True)),
                ('historyFor', models.CharField(default='history for', max_length=100, null=True)),
                ('actionTime', models.TextField(default='actionTime', null=True)),
                ('month', models.IntegerField(default=0, null=True)),
                ('year', models.IntegerField(default=0, null=True)),
                ('day', models.IntegerField(default=0, null=True)),
                ('item_marker', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0, null=True)),
                ('item_name', models.CharField(default='item', max_length=100, null=True)),
                ('price', models.BigIntegerField(default=0, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('post_price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='username', max_length=1000, null=True)),
                ('email', models.TextField(default='user@gmail.com', null=True)),
                ('city', models.TextField(default='city', null=True)),
                ('township', models.TextField(default='township', null=True)),
                ('ward', models.TextField(default='ward', null=True)),
                ('street', models.TextField(default='street', null=True)),
                ('userId', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
