# Generated by Django 4.1.7 on 2023-03-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0, null=True)),
                ('user_Name', models.TextField(default='user_name', null=True)),
                ('user_note', models.TextField(default='Notes', null=True)),
                ('date', models.TextField(default='date', null=True)),
                ('time', models.TextField(default='time', null=True)),
            ],
        ),
    ]
