# Generated by Django 4.1.7 on 2023-03-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userPswd',
            field=models.TextField(default='pswd', null=True),
        ),
    ]
